name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
    - name: Wrap Chrome
      run: chmod +x ./build/wrap_chrome.sh && ./build/wrap_chrome.sh
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/StageZero.sln
    - name: Build
      run: dotnet build ./src/StageZero.sln --no-restore
    - name: Test
      run: SE_BROWSER_PATH=$(which chrome) dotnet test ./src/StageZero.sln --no-restore
